[versions]
agp = "8.13.0"
firebaseBom = "33.15.0"
flexibleSwitch = "1.0"
kotlin = "2.2.0"
ksp = "2.2.0-2.0.2"
coreKtx = "1.16.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.1"
material = "1.12.0"
activity = "1.10.1"
constraintlayout = "2.2.1"
hilt = "2.57"
androidx-work = "2.9.0"
hilt-work = "1.2.0"
coil = "2.5.0"
roundedimageview = "2.3.0"
okhttp = "3.14.9"
soloader = "0.10.4"
fastjson = "1.1.67.android"
imagepicker = "2.3.22"
otpview = "v1.1.2-ktx"
circleimageview = "3.1.0"
awsIotSdk = "2.81.0"
viewpagerindicator = "1.2.1"
libphonenumber = "8.12.57"
segmentedbutton = "3.1.9"
slidetoact = "0.10.0"
smoothbottombar = "1.7.9"
numberpicker = "2.4.13"
glide = "5.0.5"
room = "2.7.2"
playServicesAdsIdentifier = "18.2.0"
places = "4.3.1"
circularseekbar = "1.4.2"
firebaseMessaging = "24.1.1"
firebaseCrashlyticsKtx = "latest"
firebaseAnalytics = "latest"
firebaseConfig = "22.1.2"
branchIo = "5.18.1"
samsungInstallReferrer = "4.0.0"
mpandroidchart = "v3.1.0"
androidSpinkit = "1.4.0"
swiperefreshlayout = "1.1.0"
dragdropswiperecyclerview = "1.2.0"
billingKtx = "8.0.0"
lottie = "6.4.0"
appUpdateKtx = "2.1.0"
zoomage = "1.3.1"
paletteKtx = "1.0.0"
certificatetransparency = "2.5.71"
colorwheel = "1.1.13"
googleServicesPlugin = "4.4.2"
firebaseCrashlyticsPlugin = "3.0.4"
retrofit = "2.11.0"
okhttpLogging = "4.12.0"
coroutines = "1.9.0"
lifecycle-extensions = "2.2.0"
lifecycle_version = "2.9.2"
navigation = "2.9.0"
core-splashscreen = "1.0.1"
nats = "2.21.4"
datastore = "1.1.7"
googleprotobuf = "0.9.5"
protobufjavalite = "4.31.1"
androidsecurity = "1.1.0"
multidex = "2.0.1"
mediationTestSuite = "3.0.0"
navigationSafe = "2.7.7"
workRuntimeKtx = "2.10.3"
playServicesAuthApiPhone = "18.3.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }

#hilt
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }

work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "androidx-work" }
hilt-work = { group = "androidx.hilt", name = "hilt-work", version.ref = "hilt-work" }
hilt-work-compiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "hilt-work" }

#retrofit
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }
logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttpLogging" }
okhttp-urlconnection = { group = "com.squareup.okhttp3", name = "okhttp-urlconnection", version.ref = "okhttp" }

#coroutine
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
androidx-lifecycle-process = { group = "androidx.lifecycle", name = "lifecycle-process", version.ref = "lifecycle_version" }
lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle_version" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle_version" }
lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle_version" }
#navigation
navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation" }
navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation" }
#firebase
firebase-messaging = { group = "com.google.firebase", name = "firebase-messaging", version.ref = "firebaseMessaging" }
firebase-crashlytics-ktx = { group = "com.google.firebase", name = "firebase-crashlytics-ktx", version.ref = "firebaseCrashlyticsKtx" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics", version.ref = "firebaseAnalytics" }
firebase-config = { group = "com.google.firebase", name = "firebase-config", version.ref = "firebaseConfig" }
#glide
glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }
glide-compiler = { group = "com.github.bumptech.glide", name = "compiler", version.ref = "glide" }
#room
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
google-services = { id = "com.google.gms.google-services", version.ref = "googleServicesPlugin" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebaseCrashlyticsPlugin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
googleprotobuf = { id = "com.google.protobuf", version.ref = "googleprotobuf" }
safeargs = { id = "androidx.navigation.safeargs.kotlin", version.ref = "navigationSafe" }

